// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUh6-uxUtdi-EOqGNEXC66wFpa35G3XHo',
    appId: '1:545165819994:web:e677fdd9a628636f2ad863',
    messagingSenderId: '545165819994',
    projectId: 'socialapptutorial-5b2ed',
    authDomain: 'socialapptutorial-5b2ed.firebaseapp.com',
    storageBucket: 'socialapptutorial-5b2ed.firebasestorage.app',
    measurementId: 'G-K288NK6P58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCv1s1WyJeC_5iGM3c83zBYcyTYOFWfkg',
    appId: '1:545165819994:android:809f9e12977688562ad863',
    messagingSenderId: '545165819994',
    projectId: 'socialapptutorial-5b2ed',
    storageBucket: 'socialapptutorial-5b2ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbW_kYlt2UapC3zpasqwFqbv5mgtb--x8',
    appId: '1:545165819994:ios:f0afb1f8739821332ad863',
    messagingSenderId: '545165819994',
    projectId: 'socialapptutorial-5b2ed',
    storageBucket: 'socialapptutorial-5b2ed.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
